config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :domains 
  resources :mailboxes
  resources :forwarders

  patch 'mailboxes/:id/newpassword', to: 'mailboxes#newpassword', as: 'newpassword_mailboxes'

  root 'home#index'
end

app/models/domain.rb
class Domain < ActiveRecord::Base
  has_many :mailbox, :dependent => :delete_all
  validates :name, presence: true, uniqueness: true
end

app/models/format.rb
class Format < ActiveRecord::Base
end

app/models/forwarder.rb
class Forwarder < ActiveRecord::Base
  belongs_to :domain

  def self.search(query)
    where("name like ?", "%#{query}%")
  end
end

app/models/mailbox.rb
class Mailbox < ActiveRecord::Base
  belongs_to :domain
  belongs_to :format
  validates :username, presence: true, uniqueness: true
  validates :name, presence: true

  def self.search(query)
    where("username like ?", "%#{query}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable, :timeout_in => 15.minutes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController

  def index
    @domains = Domain.all
  end

  def new
    @domain = Domain.new()
  end

  def edit
    @domain = Domain.find(params[:id])
  end

  def update
    @domain = Domain.find(params[:id])

    if @domain.update(domain_params)
      redirect_to domains_path
    else
      render 'edit'
    end
  end

  def create
    @domain = Domain.new(domain_params)

    if @domain.save
      redirect_to domains_path
    else
      render 'new'
    end
  end

  def destroy
    @domain = Domain.find(params[:id])
    @domain.destroy

    redirect_to domains_path
  end

  private
    def domain_params
      params.require(:domain).permit(:name, :description)
    end
end

app/controllers/forwarders_controller.rb
class ForwardersController < ApplicationController
  def index
    if params[:search]
      @forwarders = Forwarder.search(params[:search])
    else
      @forwarders = Forwarder.all
    end
  end

  def show
    @forwarder = Forwarder.find(params[:id])
  end

  def new
    redirect_to new_domain_path if !Domain.first
    @forwarder = Forwarder.new
  end

  def edit
    @forwarder = Forwarder.find(params[:id])
  end

  def create
    @forwarder = Forwarder.new(forwarder_params)

    if @forwarder.save
      redirect_to forwarders_path
    else
      render 'new'
    end
  end

  def update
    @forwarder = Forwarder.find(params[:id])

    if @forwarder.update(forwarder_params)
      redirect_to @forwarder
    else
      render 'edit'
    end
  end

  def destroy
    @forwarder = Forwarder.find(params[:id])
    @forwarder.destroy

    redirect_to forwarders_path
  end

  private
    def forwarder_params
      params.require(:forwarder).permit(:responsible, :name, :domain_id, :goto)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/mailboxes_controller.rb
class MailboxesController < ApplicationController
  def index
    if params[:search]
      @mailboxes = Mailbox.search(params[:search])
    else
      @mailboxes = Mailbox.order(created_at: :desc).limit(15)
    end
  end

  def show
    @mailbox = Mailbox.find(params[:id])
  end

  def new
    redirect_to new_domain_path if !Domain.first
    @mailbox = Mailbox.new
  end

  def edit
    @mailbox = Mailbox.find(params[:id])
  end

  def create
    @mailbox = Mailbox.new(mailbox_params)

    require 'digest'
    @pass = random_password
    @mailbox.password = '$5$' + Digest::SHA256.base64digest(@pass)
    if @mailbox.save
      render 'created'
    else
      render 'new'
    end
  end

  def update
    @mailbox = Mailbox.find(params[:id])

    if @mailbox.update(mailbox_params)
      redirect_to @mailbox
    else
      render 'edit'
    end
  end

  def destroy
     @mailbox = Mailbox.find(params[:id])
     @mailbox.destroy

     redirect_to mailboxes_path
  end

  def newpassword
     @mailbox = Mailbox.find(params[:id])

     require 'digest'
     @pass = random_password
     @mailbox.password = '$5$' + Digest::SHA256.base64digest(@pass)
     if @mailbox.save
       render 'newpassword'
     else
       render 'index'
     end
  end

  private
    def mailbox_params
      params.require(:mailbox).permit(:username, :password, :name, :active, :expires, :format_id, :domain_id)
    end

    def random_password
      chars = 'abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789!@#$'
      password = ''
      8.times { password << chars[rand(chars.size)] }
      password
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/forwarders_helper.rb
module ForwardersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mailboxes_helper.rb
module MailboxesHelper
end

app/views/domains/_form.html.haml
= form_for @domain, :html => { class: 'form', role: 'form' } do |f|
  - if @domain.errors.any?
    - @domain.errors.full_messages.each do |msg|
      %p.alert.alert-warning
        = msg

  .form-group
    = f.label :name, class: 'control-label'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :description, class: 'control-label'
    = f.text_field :description, class: 'form-control'
  .btn-group
    = f.submit 'Save', class: 'btn btn-default'
    = link_to 'Cancel', :back, { class: 'btn btn-default' }

app/views/domains/edit.html.haml
.page-header
  %h2 Edit 

= render 'form'

app/views/domains/index.html.haml
.page-header
  %h2 Domains

.container
  - if @domains.count == 0
    %p.alert.alert-warning
      No domain found.
  - else
    %table.table.table-striped.table-hover.table-wb
      %tr
        %th Name
        %th Description
        %th
      - @domains.each do |domain|
        %tr{ class: cycle('odd', 'even') }
          %td
            = domain.name
          %td
            = domain.description
          %td
            = link_to edit_domain_path(domain), class: 'btn btn-link btn-xs' do
              .glyphicon.glyphicon-pencil
            = link_to domain_path(domain), method: :delete, data: { confirm: 'You are about to delete a domain and all related mailboxes and forwarders. Are you sure?' }, class: 'btn btn-link btn-xs' do
              .glyphicon.glyphicon-trash

app/views/domains/new.html.haml
%h2 New domain

= render 'form'

app/views/forwarders/_form.html.haml
= form_for @forwarder, :html => { class: 'form', role: 'form' } do |f|
  - if @forwarder.errors.any?
    - @forwarder.errors.full_messages.each do |msg|
      %p.alert.alert-warning
        = msg

  .form-group
    = f.label :responsible, class: 'control-label'
    = f.text_field :responsible, class: 'form-control'
  .form-group
    = f.label :name, class: 'control-label'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label 'Domain', class: 'control-label'
    = f.collection_select :domain_id, Domain.all, :id, :name, {}, { class: 'form-control' }
  .form-group
    = f.label :goto, class: 'control-label'
    = f.text_area :goto, class: 'form-control'

  .form-group
    = f.submit 'Save', class: 'btn btn-default'
    = link_to 'Cancel', :back, { class: 'btn btn-default' }

app/views/forwarders/edit.html.haml
.page-header
  %h3 Edit mailbox

= render 'form'

app/views/forwarders/index.html.haml
.page-header
  %h3 Forwarders

- if @forwarders.count == 0
  %p.alert.alert-warning
    No forwarder found.
- else
  .container
    = form_tag forwarders_path, :method => 'get', :class => 'form-inline', id: 'search-form' do
      .form-group
        = text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search forwarder'
        = submit_tag 'Search', :name => nil, class: 'btn btn-default'
  %br
  %table.table.table-striped.table-hover.table-wb
    %tr
      %th Responsible
      %th Name
      %th Domain
      %th Goto
      %th
    - @forwarders.each do |forwarder|
      %tr{ class: cycle('odd','even') }
        %td= forwarder.responsible
        %td= forwarder.name
        %td= forwarder.domain.name
        %td= forwarder.goto
        %td
          = link_to forwarder_path(forwarder), class: 'btn btn-link btn-xs' do
            .glyphicon.glyphicon-search
          = link_to edit_forwarder_path(forwarder), class: 'btn btn-link btn-xs' do
            .glyphicon.glyphicon-pencil
          = link_to forwarder_path(forwarder), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-link btn-xs' do
            .glyphicon.glyphicon-trash

app/views/forwarders/new.html.haml
.page-header
  %h3 New forwarder

= render 'form'

app/views/forwarders/show.html.haml
.page-header
  %h3
    = @forwarder.name + '@' #@forwarder.domain.name

%table.table.table-wb
  %tr
    %th Responsible
    %td= @forwarder.responsible
  %tr
    %th Name
    %td= @forwarder.name
  %tr
    %th Domain
    %td= @forwarder.domain.name
  %tr
    %th Goto
    %td= @forwarder.goto
  %tr
    %th Created
    %td= @forwarder.created_at
  %tr
    %th Updated
    %td= @forwarder.updated_at

= link_to 'Back to list', forwarders_path, class: 'btn btn-default'

app/views/home/index.html.haml
%h1 narceja

%p
  Web based interface to manage Dovecot accounts.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Narceja
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      %nav.navbar.navbar-default
        .container-fluid
          .navbar-header
            = link_to 'narceja', root_path, class: 'navbar-brand'
          .navbar-collapse.collapse
            %ul.nav.navbar-nav
              %li.active
                = link_to 'Home', root_path
              %li.dropdown
                %a.dropdown-toggle{ data: { 'toggle': 'dropdown' } }
                  Domains
                  %span.caret
                %ul.dropdown-menu
                  %li
                    = link_to 'List', domains_path
                  %li
                    = link_to 'New', new_domain_path
              %li.dropdown
                %a.dropdown-toggle{ data: { 'toggle': 'dropdown' } }
                  Mailboxes
                  %span.caret
                %ul.dropdown-menu
                  %li
                    = link_to 'List', mailboxes_path
                  %li
                    = link_to 'New', new_mailbox_path
              %li.dropdown
                %a.dropdown-toggle{ data: { 'toggle': 'dropdown' } }
                  Forwarders
                  %span.caret
                %ul.dropdown-menu
                  %li
                    = link_to 'List', forwarders_path
                  %li
                    = link_to 'New', new_forwarder_path

            - if user_signed_in?
              %ul.nav.navbar-nav.navbar-right
                %li.active.nav-link
                  = link_to current_user.email, '#'
                %li
                  = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out navbar-link'
            - else
              %ul.nav.navbar-nav.navbar-right
                %li
                  = link_to 'Login', new_user_session_path, class: 'glyphicon glyphicon-log-in'
      - if notice
        %p.alert.alert-success
          = notice
      - if alert
        %p.alert.alert-danger
          = alert
      .container
        = yield

app/views/mailboxes/_credentials.html.haml
%p
  = @mailbox.username + '@' + @mailbox.domain.name
  with initial password
  %span.text-info
    = @pass

app/views/mailboxes/_form.html.haml
= form_for @mailbox, :html => { class: 'form', role: 'form' } do |f|
  - if @mailbox.errors.any?
    - @mailbox.errors.full_messages.each do |msg|
      %p.alert.alert-warning
        = msg

  .form-group
    = f.label :username, class: 'control-label'
    = f.text_field :username, class: 'form-control'
  .form-group
    = f.label 'Domain', class: 'control-label'
    = f.collection_select :domain_id, Domain.all, :id, :name, {}, { class: 'form-control' }
  .form-group
    = f.label :name, class: 'control-label'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :expires, class: 'control-label'
    = f.date_field :expires, class: 'form-control', value: (Time.now + 365.days).strftime('%Y-%m-%d')
  .form-group
    = f.label :format, class: 'control-label'
    = f.collection_select :format_id, Format.all, :id, :name, {}, { class: 'form-control' }
  .form-group
    = f.label :active, class: 'control-label'
    = f.check_box :active, class: 'checkbox'


  .form-group
    = f.submit 'Save', class: 'btn btn-default'
    = link_to 'Cancel', :back, { class: 'btn btn-default' }

app/views/mailboxes/created.html.haml
.page-header
  %h3.text-success New mailbox created

= render 'credentials'

= link_to 'Back to list', mailboxes_path, class: 'btn btn-default'

app/views/mailboxes/index.html.haml
.page-header
  %h3 Mailboxes

- if @mailboxes.count == 0
  %p.alert.alert-warning
    No mailbox found.
- else
  .container
    = form_tag mailboxes_path, :method => 'get', :class => 'form-inline', id: 'search-form' do
      .form-group
        = text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search username'
        = submit_tag 'Search', :name => nil, class: 'btn btn-default'
  %br
  %table.table.table-striped.table-hover.table-wb
    %tr
      %th Name
      %th Username
      %th Domain
      %th Lastlogin
      %th Expires
      %th Format
      %th Active
      %th
    - @mailboxes.each do |mailbox|
      %tr{ class: cycle('odd','even') }
        %td= mailbox.name
        %td= mailbox.username
        %td= mailbox.domain.name
        %td= mailbox.lastlogin
        %td= mailbox.expires
        %td= mailbox.format.name
        %td= mailbox.active
        %td
          = link_to mailbox_path(mailbox), class: 'btn btn-link btn-xs' do
            .glyphicon.glyphicon-search
          = link_to edit_mailbox_path(mailbox), class: 'btn btn-link btn-xs' do
            .glyphicon.glyphicon-pencil
          = link_to newpassword_mailboxes_path(mailbox), method: :patch, data: { confirm: 'You are about to reset a password. Are you sure?' }, class: 'btn btn-link btn-xs' do
            .glyphicon.glyphicon-refresh
          = link_to mailbox_path(mailbox), method: :delete, data: { confirm: 'You are about to delete a mailbox. Are you sure?' }, class: 'btn btn-link btn-xs' do
            .glyphicon.glyphicon-trash

app/views/mailboxes/new.html.haml
.page-header
  %h3 New mailbox

= render 'form'

app/views/mailboxes/newpassword.html.haml
.page-header
  %h3.text-success New password generated

= render 'credentials'

= link_to 'Back to list', mailboxes_path, class: 'btn btn-default'

app/views/mailboxes/show.html.haml
.page-header
  %h3
    = @mailbox.username + '@' + @mailbox.domain.name

%table.table.table-wb
  %tr
    %th Name
    %td= @mailbox.name
  %tr
    %th Lastlogin
    %td= @mailbox.lastlogin
  %tr
    %th Expires
    %td= @mailbox.expires
  %tr
    %th Format
    %td= @mailbox.format.name
  %tr
    %th Active
    %td= @mailbox.active
  %tr
    %th Created
    %td= @mailbox.created_at
  %tr
    %th Updated
    %td= @mailbox.updated_at

= link_to 'Back to list', mailboxes_path, class: 'btn btn-default'